### PR TITLE
Adding dependsOn capability

### PR DESCRIPTION
**Pull request by fzamperin**
Hello, I was into a project of mine and I had this requirement, I need the MaskedField to have other fields that he could depends on, for this reason I'm creating this pull request, please see if everything is okay.

Any ideas for improve are very welcome, and thanks for the initiative, this package helps me a lot

### CODE REVIEW

**Comment by greg0x46** [comment]
> Hello, I was into a project of mine and I had this requirement, I need the MaskedField to have other fields that he could depends on, for this reason I'm creating this pull request, please see if everything is okay.
> 
> Any ideas for improve are very welcome, and thanks for the initiative, this package helps me a lot

Hey there, thank you for your pull request! I really appreciate your contribution. After testing it, I noticed a couple of issues:

1. There seems to be a minor typo. Kindly take a look at my review for more details.
2. I found that when the input value is changed in the dependsOn method, the mask doesn't apply to the new value. To address this, I updated beholdr/maska to version 2. Could you please merge your pull request with dev-main?

I hope this clarifies the points I wanted to discuss. Your efforts are greatly appreciated, and I'm looking forward to resolving these issues together.

**Comment by fzamperin** [comment]
I'm very sorry I closed this PR by mistake

I had made a cast to see if this is the right behavior for the mask field.

I have a select field and the mask field dependsOn the select field, I guess the maska v2 fixed the issue, actually I was testing with Maska v2, but I didn't change the version when I created the PR.

Another thing is that I have a more complex Mask for this reason I added the ```data-maska-eager``` option enabled, we can also control this with options, then the user can set this option in the field.

In this example I used a percentage mask, and then a currency mask in BRL when the select input changes.

[Screencast from 2023-05-18 21-07-07.webm](https://github.com/greg0x46/laravel-nova-masked-field/assets/2280530/aa329460-446b-4653-996f-1490ef030d5f)

**Comment by greg0x46** [comment]
Opa, brasileiro aqui também o/
Ficou ótimo, sinta-se a vontade em avançar o status do PR, ficarei feliz em publicar a primeira contribuição deste package.

**Comment by fzamperin** [comment]
Fala Greg,

Desculpe a demora em responder, estive um pouco ocupado, muito bom, hehehe, cara acho que você pode realizar o Merge, eu não possuo permissão.

Fico feliz em ter ajudado, esse pacote me ajudou bastante aqui no projeto!!

**Pull request merged**
